---
- name: Configure systemd journal remote tls and server settings
  become: true
  ansible.builtin.template:
    src: 'templates/journal-remote.conf.j2'
    backup: true
    dest: '/etc/systemd/journal-remote.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart remotesyslogserver'

- name: Create systemd socket for rsyslog server
  become: true
  ansible.builtin.template:
    src: 'templates/systemd-journal-remote.socket.j2'
    backup: true
    dest: "/lib/systemd/system/{{ item.systemd_file }}.socket"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ journald_server__systemd_jobs }}"
  notify: 'systemctl restart remotesyslogserver'

- name: Create systemd service for rsyslog server
  become: true
  ansible.builtin.template:
    src: 'templates/systemd-journal-remote.service.j2'
    backup: true
    dest: "/lib/systemd/system/{{ item.systemd_file }}.service"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ journald_server__systemd_jobs }}"
  notify: 'systemctl restart remotesyslogserver'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify: 'systemctl restart remotesyslogserver'
