---
- name: Create /var/log/journal/remote
  become: true
  ansible.builtin.file:
    path: '/var/log/journal/remote'
    state: directory
    mode: "u=rwX,g=rX"
    recurse: true
    owner: 'systemd-journal-remote'
    group: 'systemd-journal-remote'
  notify: 'systemctl restart remotesyslogserver'
