---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install requirements
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Install requirements
  ansible.builtin.include_tasks:
    file: 'dir.yml'

- name: Start Systemd journal remote Services
  ansible.builtin.include_tasks:
    file: 'systemd.yml'

- name: Configure Systemd journal remote configuration
  ansible.builtin.include_tasks:
    file: 'config.yml'
