---
- name: Create group systemd-journal-remote
  become: true
  ansible.builtin.group:
    name: 'systemd-journal-remote'
    state: present

- name: Create User systemd-journal-remote
  become: true
  ansible.builtin.user:
    name: 'systemd-journal-remote'
    create_home: false
    group: 'systemd-journal-remote'
    groups: ['root']
    comment: 'User for uploading systemd logs'
    home: '/run/systemd'
    shell: '/usr/sbin/nologin'
    system: true
