---
- name: "Restart systemd services for rsyslog"
  listen: 'systemctl restart remotesyslogserver'
  become: true
  ansible.builtin.systemd:
    name: "{{ item.systemd_file }}"
    state: 'restarted'
  when: ansible_service_mgr == "systemd"
  with_items: "{{ journald_server__systemd_jobs }}"
